# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47cc28c1ce9b3b77784c2af3be6c0f5328c76f129f5e3231349fc9dbb32799673e361d5eb4a544590264b41e81bc8ab5abe438e403467eaacdab5f6b399173c6

test:
  secret_key_base: 6f030f1f929a068737768437516122c43e5827335eee9f4c4da2822b16ab225ecdb783ccb552387ebc3f364c9bc12087d1a6d6ed3ecd8dc61068f6c756ad0260

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
